project:
  type: website
  output-dir: docs

website:
  title: "Introduction to Machine Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 6




